### ISSUE TITLE
Opening With .PNGs

### ISSUE THREAD

**Issue by Fezodge** [Brackeys/UPAToolkit#8]
Hello, 
I'd like to start off by saying that I think this extension is very good, and is extremely useful when it comes to editing sprites, without the need to delete the current item, change it in another application, and then add it back in again.

But, there is one thing that annoys me, and that's the fact that you can't open a .png file, which practically all my sprites are. This basically defies the point, unless of course you first made it in Unity, and so have the .asset file.

My solution to this would simply to have an option to open .pngs, as well as the .asset option (with .jpeg and .psd ect). I'm not really sure why this wasn't in there in the first place, but I'm sure you had your reasons.

Let me know what you think,

Fezodge III

**Comment by Frozenfire92** [comment]
This is already in the [todo list](https://github.com/Brackeys/UPAToolkit/blob/master/TODO.md)

**Comment by Fezodge** [comment]
Oh right. I didn't see that. Any idea of when this might be done, because this is kinda pintless at the moment.

**Comment by Frozenfire92** [comment]
No idea, @ATBrackeys hasn't commited to this repo in a while. I may be able to have a look this weekend at implementing it. I would suggest you do the same and report back any findings (I haven't looked at the code before)

**Comment by Xenira** [comment]
Ill have another look at this as well.

**Comment by Fezodge** [comment]
Will do.

**Comment by Xenira** [comment]
I have created a pull request for this issue. Here is the commit: 28aa21bca27a592047a2eb7c188e55e74a200611

**Comment by ATBrackeys** [comment]
:+1:
